export { Header } from './header/Header';
export { Layout } from './layout/Layout';
export { LoginPage } from './auth/loginPage/LoginPage';
export { MainPage } from './mainPage/MainPage';
export { MoviePage } from './moviePage/MoviePage';
export { RegistrationPage } from './auth/registrationPage/RegistrationPage';
export { SavedMoviesPage } from './savedMoviesPage/SavedMoviesPage';
export { SearchMoviesPage } from './searchMoviesPage/SearchMoviesPage';
export { CategoryPage } from './categoryPage/CategoryPage';
